###########################################################
# Projet-Labo 02 - Routeur Debian & pfSense
# Fichier : /etc/sysctl.conf
#
# Description :
# Activation du routage IPv4 afin de transformer
# le système Debian en routeur.
###########################################################

# Activer le routage IPv4
net.ipv4.ip_forward = 1
