// =========================================================
// Projet-Labo-01-04-DNS-DDNS
// Serveur DNS primaire
// Fichier : /etc/bind/named.conf
//
// Description :
// Fichier principal de configuration de Bind9.
// Il charge les différentes configurations et zones DNS.
// =========================================================


// Configuration des options globales
include "/etc/bind/named.conf.options";


// Déclarations des zones DNS
include "/etc/bind/named.conf.local";


// Zones par défaut de Bind9
include "/etc/bind/named.conf.default-zones";
