# =========================================================
# Projet-Labo-01-4-DNS-DDNS
# Serveur DNS primaire
# Fichier : /etc/resolv.conf
#
# Description :
# Configuration du résolveur DNS local.
# Le serveur DNS primaire utilise son propre
# service Bind9 pour la résolution des noms.
# =========================================================

search tarantino.family

nameserver 127.0.0.1
