# =========================================================
# Projet-Labo-01-04-DNS-DDNS
# Serveur DNS secondaire
# Fichier : /etc/resolv.conf
#
# Description :
# Configuration de la résolution DNS locale.
# =========================================================

search tarantino.family

nameserver 127.0.0.1
