# =========================================================
# Projet-Labo 03 - Serveur DHCP Linux
# Fichier : /etc/dhcp/dhcpd.conf
#
# Description :
# Configuration du serveur DHCP distribuant
# automatiquement les paramètres réseau aux
# clients du réseau 192.168.12.0/24.
# =========================================================

# Nom de domaine attribué aux clients DHCP
option domain-name "tarantino.family";

# Adresse IP du serveur DNS
option domain-name-servers 192.168.11.250;

# Durée du bail par défaut (10 minutes)
default-lease-time 600;

# Durée maximale du bail (2 heures)
max-lease-time 7200;

# Autorité DHCP sur le réseau
authoritative;

# Configuration du réseau
subnet 192.168.12.0 netmask 255.255.255.0 {

    # Plage d'adresses distribuées par le serveur DHCP
    range 192.168.12.12 192.168.12.62;

    # Passerelle par défaut
    option routers 192.168.12.254;

    # Adresse de broadcast
    option broadcast-address 192.168.12.255;
}
