# =========================================================
# Projet-Labo-01-04-DNS-DDNS
# Serveur DHCP + DDNS
# Fichier : /etc/dhcp/dhcpd.conf
#
# Description :
# Configuration du serveur DHCP ainsi que des
# mises à jour dynamiques DNS (DDNS).
# =========================================================


# =========================================================
# Configuration générale du DHCP
# =========================================================

option domain-name "tarantino.family";

option domain-name-servers 192.168.11.250, 192.168.12.250;

default-lease-time 600;
max-lease-time 7200;

authoritative;


subnet 192.168.11.0 netmask 255.255.255.0 {

    range 192.168.11.5 192.168.11.15;

    option routers 192.168.11.254;
}


# =========================================================
# Configuration DDNS
# =========================================================

key "cle_dhcp" {
    algorithm hmac-sha256;
    secret "A_REMPLACER_PAR_LA_CLE_TSIG";
};

ddns-update-style interim;

ddns-domainname "tarantino.family.";

ddns-rev-domainname "11.168.192.in-addr.arpa.";

allow client-updates;

zone tarantino.family. {
    primary 192.168.11.250;
    key cle_dhcp;
}

zone 11.168.192.in-addr.arpa. {
    primary 192.168.11.250;
    key cle_dhcp;
}
