#!/usr/sbin/nft -f

# =========================================================
# Projet-Labo-01-04-DNS-DDNS
# Routeur Debian
# Fichier : /etc/nftables.conf
#
# Description :
# Configuration du pare-feu et du NAT
# permettant le routage entre les réseaux
# internes et le réseau WAN.
# =========================================================

flush ruleset


table inet filter {

    chain input {
        type filter hook input priority filter;
    }

    chain forward {
        type filter hook forward priority filter;
    }

    chain output {
        type filter hook output priority filter;
    }
}


table ip nat-pat {

    chain nat {
        type nat hook postrouting priority srcnat;

        oifname "enp0s3" masquerade
    }
}
