# =========================================================
# Projet-Labo-01-04-DNS-DDNS
# Routeur Debian
# Fichier : /etc/sysctl.conf
#
# Description :
# Activation du routage IPv4 permettant au
# serveur Debian de fonctionner comme routeur.
# =========================================================

# Activation du routage IPv4
net.ipv4.ip_forward = 1
